/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as StandardRouteImport } from './routes/standard'
import { Route as IndexRouteImport } from './routes/index'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardRoute = StandardRouteImport.update({
  id: '/standard',
  path: '/standard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/standard': typeof StandardRoute
  '/vip': typeof VipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/standard': typeof StandardRoute
  '/vip': typeof VipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/standard': typeof StandardRoute
  '/vip': typeof VipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/standard' | '/vip'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/standard' | '/vip'
  id: '__root__' | '/' | '/standard' | '/vip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StandardRoute: typeof StandardRoute
  VipRoute: typeof VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard': {
      id: '/standard'
      path: '/standard'
      fullPath: '/standard'
      preLoaderRoute: typeof StandardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StandardRoute: StandardRoute,
  VipRoute: VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
